
# maql generated by the java client from the department example 
maql = """
# THIS IS MAQL SCRIPT THAT GENERATES PROJECT LOGICAL MODEL.
# SEE THE MAQL DOCUMENTATION AT http://developer.gooddata.com/api/maql-ddl.html FOR MORE DETAILS

# CREATE DATASET. DATASET GROUPS ALL FOLLOWING LOGICAL MODEL ELEMENTS TOGETHER.
CREATE DATASET {dataset.department} VISUAL(TITLE "Department");

# CREATE THE FOLDERS THAT GROUP ATTRIBUTES AND FACTS
CREATE FOLDER {dim.department} VISUAL(TITLE "Department") TYPE ATTRIBUTE;


# CREATE ATTRIBUTES.
# ATTRIBUTES ARE CATEGORIES THAT ARE USED FOR SLICING AND DICING THE NUMBERS (FACTS)
CREATE ATTRIBUTE {attr.department.department} VISUAL(TITLE "Department", FOLDER {dim.department}) AS KEYS {f_department.id} FULLSET;
ALTER DATASET {dataset.department} ADD {attr.department.department};

# CREATE FACTS
# FACTS ARE NUMBERS THAT ARE AGGREGATED BY ATTRIBUTES.
# CREATE DATE FACTS
# DATES ARE REPRESENTED AS FACTS
# DATES ARE ALSO CONNECTED TO THE DATE DIMENSIONS
# CREATE REFERENCES
# REFERENCES CONNECT THE DATASET TO OTHER DATASETS
# ADD LABELS TO ATTRIBUTES
ALTER ATTRIBUTE {attr.department.department} ADD LABELS {label.department.department.name} VISUAL(TITLE "Name") AS {f_department.nm_name};

ALTER ATTRIBUTE  {attr.department.department} DEFAULT LABEL {label.department.department.name};
ALTER ATTRIBUTE {attr.department.department} ADD LABELS {label.department.department} VISUAL(TITLE "Department") AS {f_department.nm_department}; 
# SYNCHRONIZE THE STORAGE AND DATA LOADING INTERFACES WITH THE NEW LOGICAL MODEL
SYNCHRONIZE {dataset.department};
"""

# data generated by the java client from the department example 
data = '''"department","name"
"d1","HQ General Management"
"d2","HQ Information Systems"
"d3","HQ Marketing"
"d4","HQ Human Resources"
"d5","HQ Finance and Accounting"
"d11","Store Management"
"d14","Store Information Systems"
"d15","Store Permanent Checkers"
"d16","Store Temporary Checkers"
"d17","Store Permanent Stockers"
"d18","Store Temporary Stockers"
"d19","Store Permanent Butchers"'''

# getSLIManifest in SLI.java
sli_manifest = {"dataSetSLIManifest": {
                   "parts": [{"columnName": "department",
                              "mode": "FULL",
                              "populates": ["label.department.department"],
                              "referenceKey": 1
                              },
                              {"columnName": "name",
                               "mode": "FULL",
                               "populates": ["label.department.department.name"]
                               }
                              ],
                    "file": "data.csv",
                    "dataSet": "dataset.department",
                    "csvParams": {"quoteChar": '"',
                                  "escapeChar": '"',
                                  "separatorChar": ",",
                                  "endOfLine": "\n"
                                  }
                    }}